[package]
name = "rust-template"
edition = "2021"
version = "0.1.0"
authors = ["cooperwalbrun"]
description = "A template repository for creating new Rust projects."
documentation = "https://github.com/cooperwalbrun/rust-template/blob/master/README.md"
homepage = "https://github.com/cooperwalbrun/rust-template"
repository = "https://github.com/cooperwalbrun/rust-template"
readme = "README.md"
license-file = "LICENSE"
exclude = ["/.github/*", "/Makefile.toml", "/clippy.toml", "/rustfmt.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
mockito = "0.7.0"
