[package]
name = "your-package-name"
edition = "2021"
version = "0.1.0"
authors = ["your name or pseudonym"]
description = "A short description of your project."
documentation = "https://github.com/cooperwalbrun/rust-template/blob/master/README.md"
homepage = "https://github.com/cooperwalbrun/rust-template"
repository = "https://github.com/cooperwalbrun/rust-template"
readme = "README.md"
license-file = "LICENSE"
exclude = ["/.github/*", "/Makefile.toml", "/clippy.toml", "/rustfmt.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# If this is a library, it is recommended to use https://github.com/dtolnay/thiserror
# If this is NOT a library (i.e. an application), it is recommended to use https://github.com/dtolnay/anyhow

[dev-dependencies]
mockito = "0.7.0"
