# Documentation for the settings in this file can be found here: https://github.com/rust-lang/rust-clippy#configuration
# Some configuration is not supported (yet) by this file, so refer to src/lib.rs for the rest.

cognitive-complexity-threshold = 20
